ch-ch-ch-ch-changes

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,10 +1,34 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
+this_dir=$(cd $(dirname $0); pwd -P)
+source=$this_dir/config
 link="ln -svf"
-source=$(cd $(dirname $0); pwd -P)/dotfiles
+arch=$(uname -s)
+host=
 excludes="$0 README.md bin applescript samples"
-type=$(uname -s)
 packages_darwin="htop vim bash bash-completion tree wget curl git jq iperf packer terraform consul awscli"
+exec=
+
+while getopts ":tb:" opt; do
+    case $opt in
+    t)
+        exec=echo
+        ;;
+    b)
+        value=$OPTARG
+        ;;
+    \?)
+        echo "Invalid option: -$opt" >&2
+        exit 1
+        ;;
+    :)
+        echo "Option -$opt requires an argument." >&2
+        exit 1
+        ;;
+    esac
+done
+shift $(($OPTIND - 1))
+
 
 # development packages
 # brew cask install java
@@ -24,77 +48,71 @@ function check_file {
 		if [ -d "$base/$file" ]; then
 			link_dotfiles $1 $path
 		elif [ -f "$base/$file" ]; then
-			$link $base/$file ~/.$path
+			echo $link $base/$file ~/.$path
 		else
 			echo "Cannot find $base/$file."
 		fi
 	fi
 }
 
+function scan_files {
+  echo "================================================================================"
+	echo "--- scan_files $@ ---"
+	echo "--------------------------------------------------------------------------------"
+
+  local base=$1
+  if [ -n "$2" ]; then
+    local pred="-name \"$type.*\""
+  else
+    local tag=""
+  fi
+
+  echo "Scanning directory $base ... $tag"
+  for file in $(find $base -maxdepth 1 -type f $pred -exec basename {} ';'); do
+    echo "$HOME/.$file --> $base/$file"
+  done
+}
+
 function link_dotfiles {
 	echo "--------------------------------------------------------------------------------"
-	echo "--- Scanning $1 --- $2 ---"
+	echo "--- Linking dotfiles in $1 "
 	echo "--------------------------------------------------------------------------------"
-	if [ -n "$2" ]; then
-		if [ ! -d ~/.$2 ]; then
-			echo "Path ~/.$2 does not exist, skipping..."
-			return
-		fi
-		local base="$1/$2"
-	else
-		local base=$1
-	fi
-	if [ ! -d $base ]; then
-		echo "$base directory does not exist, skipping..."
-		return
-	fi
-	echo "Scanning directory $base ..."
-	local noarch_files=$(ls $base | grep -v Linux | grep -v Darwin)
-	local arch_files=$(ls $base | grep $type)
-  for file in $noarch_files; do
-    echo "noarch - $file"
-  #   if [ -n "$2" ]; then
-  #     local path="$2/$file"
-  #   else
-  #     local path=$file
+  
+  # if [ -n "$2" ]; then
+  #   if [ ! -d ~/.$2 ]; then
+  #     echo "Path ~/.$2 does not exist, skipping..."
+  #     return
   #   fi
-  #   if [[ $excludes =~ $file ]]; then
-  #     echo "Excluding $base/$file."
-  #   else
-  #     if [ -d "$base/$file" ]; then
-  #       scan_directory $1 $path
-  #     elif [ -f "$base/$file" ]; then
-  #       $link $base/$file ~/.$path
-  #     else
-  #       echo "Cannot find $base/$file."
-  #     fi
-  #   fi
+  #   local base="$1/$2"
+  # else
+  #   local base=$1
+  # fi
+
+  local base=$1/dotfiles
+  declare -A dotfiles
+  
+  # if [ ! -d $base ]; then
+  #   echo "$base directory does not exist, skipping..."
+  #   return
+  # fi
+
+  for file in $(find $base -mindepth 1 -maxdepth 1 -type f -not -name "*.*" -exec basename {} ';'); do
+    dotfiles[$HOME/.$file]=$base/$file
   done
-  for file in $arch_files; do
-    echo "arch - $file"
-  #   if [ -n "$2" ]; then
-  #     local path="$2/$file"
-  #   else
-  #     local path=$file
-  #   fi
-  #   if [[ $excludes =~ $type.$file ]]; then
-  #     echo "Excluding $base/$file."
-  #   else
-  #     if [ -d "$base/$file" ]; then
-  #       scan_directory $1 $path
-  #     elif [ -f "$base/$file" ]; then
-  #       $link $base/$file ~/.${path#$type.*}
-  #     else
-  #       echo "Cannot find $base/$file."
-  #     fi
-  #   fi
+
+  for type in $arch $host; do
+    for file in $(find $base -mindepth 1 -maxdepth 1 -type f -name "$type.*" -exec basename {} ';'); do
+      dotfiles[$HOME/${file#$type*}]=$base/$file
+    done
   done
   
-  declare -A animals=( ["moo"]="cow" ["woof"]="dog")
-  echo "${animals[moo]}"
-  for sound in "${!animals[@]}"; do echo "$sound - ${animals[$sound]}"; done
+  for dotfile in "${!dotfiles[@]}"; do 
+    $exec $link ${dotfiles[$dotfile]} $dotfile
+  done
   
-	echo "Done with $base."
+	echo "--------------------------------------------------------------------------------"
+	echo "--- Done with $base."
+  echo
 }
 
 function install_packages {
